services:
    postgres:
        image: postgres:15
        container_name: rhythmeo-postgres
        restart: always
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        env_file:
            - .env
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
