services:
    postgres:
        image: postgres:15
        container_name: rhythmeo-postgres-dev
        restart: always
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        env_file:
            - .env
        ports:
            - '5432:5432'
        volumes:
            - postgres_data_dev:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME}']
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: rhythmeo-app-dev
        restart: always
        ports:
            - '4200:4200'
            - '3000:3000'
        environment:
            - NODE_ENV=development
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
        env_file:
            - .env
        volumes:
            - ./src:/app/src
            - ./server:/app/server
            - ./angular.json:/app/angular.json
            - ./tsconfig.json:/app/tsconfig.json
            - ./tsconfig.app.json:/app/tsconfig.app.json
            - ./ormconfig.ts:/app/ormconfig.ts
            - ./ormconfig.js:/app/ormconfig.js
            - ./.postcssrc.json:/app/.postcssrc.json
        depends_on:
            postgres:
                condition: service_healthy

volumes:
    postgres_data_dev:
